name: "构建Docker镜像并推送至Docker hub"

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v3

      - name: 初始化QEMU
        uses: docker/setup-qemu-action@v2

      - name: 初始化Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 登录Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 初始化镜像元数据
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ochh/sentinel-dashboard
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=tag,prefix=v

      - name: 构建并发布镜像
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          build-args: |
            SENTINEL_DASHBOARD_VERSION=${{github.ref_name}}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
